MLTIManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MLTIManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'ProcessManager.views.home_page', name='home_page'),
    url(r'^asset/(\d+)/new$', 'ProcessManager.views.add_accessory', name='add_accessory'),
    url(r'^asset/(\d+)/remove$', 'ProcessManager.views.remove_accessory', name='remove_accessory'),
    url(r'^asset/(\d+)/$', 'ProcessManager.views.asset', name='asset'),
    url(r'^search/asset/$', 'ProcessManager.views.search_asset', name='search_asset'),
    url(r'^search/person/$', 'ProcessManager.views.search_person', name='search_person'),
    url(r'^search/checkin/(\d+)/person/$', 'ProcessManager.views.checkin_search_person', name='checkin_search_person'),
    url(r'^person/(\d+)/$', 'ProcessManager.views.person', name='person'),
    url(r'^select_person/(\S+)/$', 'ProcessManager.views.select_person', name='select_person'),
    url(r'^person/$', 'ProcessManager.views.select_person', name='all_people'),
    url(r'^import', 'ProcessManager.views.import_files', name='import_files'),
    url(r'^assignment/(\d+)/end_date$', 'ProcessManager.views.assignment_end_date', name='assignment_end_date'),
    url(r'checkin/new$', 'ProcessManager.views.new_check_in', name='new_check_in'),
    url(r'checkin/(\d+)/$', 'ProcessManager.views.existing_check_in', name='existing_check_in'),
    url(r'checkin/(\d+)/(\d+)$', 'ProcessManager.views.device_check_in', name='device_check_in'),
    url(r'^checkin/(\d+)/select_person/(\S+)/$', 'ProcessManager.views.checkin_select_person', name='checkin_select_person'),
    url(r'^checkin/(\d+)/select_person/$', 'ProcessManager.views.checkin_select_person', name='checkin_select_person'),
    url(r'^checkin/(\d+)/(\d+)/save$', 'ProcessManager.views.save_check_in_results', name='check_in_save'),


    url(r'^admin/', include(admin.site.urls)),
)

ProcessManager/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
# Create your models here.

class DeviceType(models.Model):
    name = models.TextField(default='')
    description = models.TextField(default='')

    def __str__(self):
        return u'%s %s' % (self.name, self.description)


class Asset(models.Model):
    tag = models.IntegerField()
    description = models.TextField(default='')
    wifi_address = models.TextField(default='')
    bluetooth_address = models.TextField(default='')
    type = models.ForeignKey(DeviceType)
    passcode = models.TextField(default='')

    def __str__(self):
        return '{0}'.format(self.tag)

class Person(models.Model):
    last_name = models.TextField(default='')
    first_name = models.TextField(default='')
    middle_name = models.TextField(default='')
    student_number = models.TextField(default='')
    birthdate = models.DateField(default='1990-01-01',
                                 null=True)

    def __str__(self):
        return ('{last_name}, {first_name} : {student_number}').format(
            last_name=self.last_name, first_name=self.first_name, student_number=self.student_number)


class Note(models.Model):
    person = models.ForeignKey(Person)
    content = models.TextField('')
    json_details = models.TextField('')

    def __str__(self):
        return 'Note about {first_name} {last_name}'.format(first_name=self.first_name, last_name=self.last_name)


class Assignment(models.Model):
    person = models.ForeignKey(Person, default='')
    asset = models.ForeignKey(Asset, related_name='asset_assignment', default='')
    note = models.TextField(default='')
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True)

    def clean(self):
        #Check that end date is after start date.
        if self.end_date is not None and self.end_date <= self.start_date:
            raise ValidationError('End date must be after start date.')
        else:
            pass

    def __str__(self):
        return '{asset} assigned to {first_name} {last_name} from {start_date} to {end_date}'.format(
            asset=self.asset.tag,
            first_name=self.person.first_name, last_name=self.person.last_name,
            start_date=self.start_date, end_date=self.end_date
        )

    @property
    def active(self):
        if (self.end_date is None or self.end_date >= timezone.now()) \
                and (self.start_date is None or self.start_date < timezone.now()):
            return True
        else:
            return False



class Accessory(models.Model):
    name = models.TextField(default='', null=False)
    asset = models.ForeignKey(Asset, null=True)

    def __str__(self):
        return '{name} for {asset}'.format(name=self.name, asset=self.asset.tag)


class CheckIn(models.Model):
    end_date = models.DateField(null=True)
    start_date = models.DateField(default=timezone.datetime.now().date(), null=False)
    note = models.TextField(null=True)

    def clean(self):
        #Check that end date is after start date.
        if self.end_date is not None and self.end_date <= self.start_date:
            raise ValidationError('End date must be after start date.')
        else:
            pass


    def __str__(self):
        return 'Checkin from {start_date} to {end_date}'.format(start_date=self.start_date, end_date=self.end_date)


class DeviceCheckIn(models.Model):
    MISSING = 'M'
    DAMAGED = 'D'
    PRESENT = 'P'
    STATUS_CHOICES = (
        (DAMAGED, 'Damaged'),
        (PRESENT, 'Present'),
        (MISSING, 'Missing'),
    )
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    assignment = models.ForeignKey(Assignment)
    check_in = models.ForeignKey(CheckIn)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    warranty = models.BooleanField(blank=True, default=False)


    class Meta:
        unique_together = (("assignment", "check_in"),)


    def __str__(self):
        return '{status} of {asset} for {check_in}. Last modified {last_modified}'.format(status=self.status,
                                                                                          asset=self.assignment.asset.tag,
                                                                                          check_in = self.check_in.id,
                                                                                          last_modified=self.last_modified
                                                                                          )


class AccessoryCheckIn(models.Model):
    MISSING = 'M'
    DAMAGED = 'D'
    PRESENT = 'P'
    STATUS_CHOICES = (
        (DAMAGED, 'Damaged'),
        (PRESENT, 'Present'),
        (MISSING, 'Missing'),
    )
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    assignment = models.ForeignKey(Assignment)
    accessory = models.ForeignKey(Accessory)
    check_in = models.ForeignKey(CheckIn)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2, blank=True)
    warranty = models.BooleanField(blank=True, default=False)

    class Meta:
        unique_together = (("assignment", "accessory", "check_in"),)

    def __str__(self):
        return '{status} {accessory} of {asset} for {check_in}. Last modified {last_modified}'.format(status=self.status,
                                                                                                      accessory=self.accessory.name,
                                                                                          asset=self.assignment.asset.tag,
                                                                                          check_in = self.check_in.id,
                                                                                          last_modified=self.last_modified
                                                                                          )

class CheckInNote(models.Model):
    check_in = models.ForeignKey(CheckIn)
    assignment = models.ForeignKey(Assignment)
    content = models.TextField()

    unique_together = (("assignment", "check_in"),)

    def __str__(self):
        return self.content

ProcessManager/forms.py
__author__ = 'matt'

from django import forms
from ProcessManager.models import Assignment, CheckIn, DeviceCheckIn, AccessoryCheckIn, CheckInNote
from django.forms.models import modelformset_factory, BaseModelFormSet


class DataUploadForm(forms.Form):
    CHOICES=(
        ('Person', 'People'),
        ('DeviceAssignments', 'Device Assignments'),
        ('Assets', 'Assets'),
        ('DeviceType', 'Device Types')
    )

    upload_type = forms.ChoiceField(choices=CHOICES, required=True, help_text='Select the type of upload.')

    file = forms.FileField(
        widget=forms.FileInput(attrs={'id' : 'id_select_person_upload',
                                      'placeholder' : 'Upload a file.',
                                      'class' : 'form-control input-lg'})

    )


class AssignmentForm(forms.models.ModelForm):

    class Meta:
        model = Assignment
        fields = ('end_date',)


class CheckInForm(forms.models.ModelForm):

    class Meta:
        model = CheckIn
        fields = ('start_date', 'end_date', 'note')
        widgets= {
            'start_date': forms.TextInput(attrs={'class': 'form-control date_picker'}),
            'end_date': forms.TextInput(attrs={'class': 'form-control date_picker'}),
            'note': forms.Textarea(attrs={'class': 'form-control', 'rows': 2})
          }



class DeviceCheckInForm(forms.models.ModelForm):
    status = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice_check'}), choices=AccessoryCheckIn.STATUS_CHOICES, )

    class Meta:
        model= DeviceCheckIn
        fields = {'status', 'warranty'}
        attrs= {'warranty' : {'class': 'choice_check'}}


class AccessoryCheckInForm(forms.models.ModelForm):
    status = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice_check'}), choices=AccessoryCheckIn.STATUS_CHOICES, )

    class Meta:
        model = AccessoryCheckIn
        fields = {'status', 'warranty', 'id'}
        attrs= {'warranty' : {'class': 'choice_check'}}

        #widgets = {'warranty': forms.BooleanField(attrs={'class': 'choice_check'}),}


class CheckInNoteForm(forms.models.ModelForm):

    class Meta:
        model = CheckInNote
        fields = {'content' }
        widgets= {'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5})}

ProcessManager/templates/ProcessManager/base.html
<!DOCTYPE html>
<!--suppress HtmlUnknownTarget -->
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <title>{% block title %}  {% endblock %}</title>
    {% load staticfiles %}
    <script src="{% static 'scripts/jquery-2.1.0.js'%}"></script>
    <script src="{% static 'scripts/jquery.tablesorter.js' %}"></script>
    <script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
    <script src="{% static 'scripts/custom.js' %}"></script>
    <script src="{% static 'scripts/photocapture.js' %}"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">
    <link href="{% static 'css/test.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>
  <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
          <!--Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only"> Toggle Navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"> RSU1</a>
          </div>
          <!-- Collect the nav links, forms and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li class="active"><a href="/">Dashboard</a></li>
                  <li class="dropdown">
              </ul>
              <ul class="nav navbar-nav">
                  <li class=""><a id='id_import' href="/import">Import</a></li>
              </ul>



            {% block search_bar %}
                <form class="navbar-form navbar-right" role="search" method="post"
                      action="{% block asset_search_action %} /search/asset/" {% endblock %}>
                    <div class="form-group">
                            <input type="text" class="form-control" id="id_search_box" name='asset_tag' placeholder="Search for an asset" autofocus="">
                            {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-default"> Search</button>
                    </form>


                    <form class="navbar-form navbar-right" role="search" method="post"
                          action="{% block person_search_action %}/search/person/ {% endblock %}">
                        <div class="form-group form-inline" style="display:inline;">
                            <input type="text" class="form-control" id="id_person_search_box" name="last_name" placeholder="Search for a Person">
                            {% csrf_token %}
                        </div>
                        <button type="submit" class="btn btn-default"> Search</button>
                    </form>
            {% endblock %}





            </div>

      </div>
</nav>



<div class="container-fluid">
  {% block content %} {%  endblock %}
</div>




    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

ProcessManager/templates/ProcessManager/checkin.html
{% extends 'ProcessManager/base.html' %}
{% load staticfiles %}

{% block title %} Asset Check In {% endblock %}

{% block person_search_action %} {% url 'checkin_search_person' check_in.id %}{% endblock %}



{% block content %}
{% if assignment_information and check_in %} {# Only display this if we have those fields loaded. #}
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"> PERSON INFORMATION </div>
                <div class="panel-body">
                    <img src="{% static 'person_pictures/' %}{{ person_information.student_number }}.jpg"
                         class="img-rounded thumbnail img-responsive col-md-2 col-sm-2 col-xs-2"
                         alt="{{ person_information.student_number }}">
                    <div class="col-md-10 col-sm-10 col-xs-10">
                        <table class="table table-striped table-bordered table-condensed table-responsive"
                               id="id_person_table">
                            <tr><td>Name</td><td>
                                {{ person_information.first_name}}
                                {{ person_information.middle_name|slice:":1" }}
                                {{ person_information.last_name }}</td></tr>
                            <tr><td>Student Number</td><td>
                                {{ person_information.student_number }}</td></tr>
                            <tr><td>Date of Birth</td><td>{{ person_information.birthdate }}</td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">Asset Information For: {{ assignment_information.asset.tag }}</div>
                <div class="panel-body">
                    <table class="table table-striped table-responsive table-bordered table-condensed" id="id_asset_table">
                        <tr> <td> Asset </td> <td> {{ assignment_information.asset.tag }}</td></tr>
                        <tr> <td> Type  </td> <td> {{ assignment_information.asset.type }} </td></tr>
                        <tr> <td> Assignment </td> <td> {{assignment_information.start_date}} to {{ assignment_information.end_date }}</td></tr>
                    </table>
                </div>
            </div>
        </div>
    </div>



    <div class="row" id="id_item_status_table">
        <div class="col-md-6 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form id="id_save_assigment_check" action="
                    {% url 'check_in_save' check_in.id assignment_information.id %}

                    " method="POST">
                    {% csrf_token %}
                    <table class="table table-bordered table-condensed" id="id_check_in_table">
                        <thead>
                            <tr> <th> Item </th> <th> Status </th></tr>
                        </thead>
                            <tr> <td> {{ assignment_information.asset.type.name }}</td>
                                <td>

                                    <div class="btn-toolbar btn-group-sm">
                                        <div class="btn-group btn-group-sm center" data-toggle="buttons">
                                        {% for choice in DeviceForms.status %}
                                            {{ choice }}
                                            {{ choice.initial }}
                                        {% endfor %}


                                        </div>

                                       <div class="btn-group btn-group-sm" "role="radiogroup" aria-label="Warranty Repair" data-toggle="buttons">
                                          <label for="id_devices-warranty" name="warranty_check" class="btn btn-primary" id="id_asset_warranty_{{ assignment_information.asset.id }}">


                                              {{ DeviceForms.warranty }}
                                            {{ DeviceForms.warranty.initial }}
                                              Warranty 



                                           {% for hidden in DeviceForms.hidden_fields %}
                                                {{ hidden }}
                                            {% endfor %}

                                          </label>
                                       </div>

                                    </div>

                                </td></tr>



                            <tr> <td>
                            {{ AccessoryFormSet.management_form }}

                            {% if accessory_information.count > 0 %}
                            <strong>Accessor{{ accessory_information|pluralize:"y,ies" }}</strong></td><td></td></tr>
                            {% endif %}

                            {%  for accessory in accessory_information %}
                                {% for form in AccessoryFormSet %}
                                    {% if form.instance.accessory == accessory %}


                                <tr> <td> {{ accessory.name }}</td>
                                    <td>

                                    <div class="btn-toolbar btn-group-sm">
                                        <div class="btn-group btn-group-sm center" data-toggle="buttons">
                                        {% for choice in form.status %}
                                            {{ choice }}
                                            {{ choice.initial }}
                                        {% endfor %}


                                        </div>

                                       <div class="btn-group btn-group-sm"  role="radiogroup" aria-label="Warranty Repair" data-toggle="buttons">
                                          <label class="btn btn-primary" name="warranty_check" id="id_accessory_warranty_{{ accessory.id }}">
                                            {{ form.warranty }} {{ form.warranty.initial }}{{ form.warranty.label }}
                                        {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                        {% endfor %}

                                          </label>
                                       </div>


                                    </div>


                                </td></tr>
                                    {% endif %} {# end if formset #}
                                    {% endfor %} {# end for formset #}
                            {% endfor %}
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-6 col-sm-12" id="id_item_summary_table">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="panel panel-default">
                        <div class="panel-body" id="id_check_in_summary">
                            <p> <strong> Summary Information: </strong> </p>

                            <p> No Damage. </p>
                            <p> Please start the check in. </p>
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="id_notes">Notes:</label>
                        {{ NoteForm.content }}
                    </div>
            </form> {# end enclosing form #}

                    <div class="btn-group">
                        <button id="id_save_and_print" type="button" class="btn btn-primary"  aria-expanded="false" onclick=document.forms["id_save_assigment_check"].submit()>
                        Save & Print
                        </button>
                        <button id="id_save_button_dropdown" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                        <li>
                            <a id="id_save" onclick=document.forms["id_save_assigment_check"].submit() >Save</a>
                        </li>
                        </ul>
                    </div>


                    <div class="btn-group">
                        <button id="id_cancel" type="button" class="btn btn-warning"> Cancel </button>
                    </div>



                </div>
            </div>
        </div>
    </div>
 {% endif %} {# End display limitation #}





    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"> Check In Status {done} of {total} </div>
                <div class="panel-body">
                    <table class="table table-responsive table-bordered table-striped">
                        <thead>
                        <tr> <th> Person </th> <th> Asset </th> <th> When </th> <th> Device </th> <th> Accessories</th></tr>
                        </thead>



                        <!-- This is where you loop through the status. Set dataURL to checkin  record for that-->
                        {% for result in ProgressResults %}
                        <tr class="clickable_row" data-url="{% url 'device_check_in' result.device.check_in.id result.device.assignment.id %}">
                            <td> {{ result.device.assignment.person.last_name }}, {{ result.device.assignment.person.first_name  }} </td>
                            <td> {{ result.device.assignment.asset.tag }} </td>
                            <td> {{ result.device.last_modified}} </td>
                            <td> <p> {{ result.device.get_status_display|default:"Not Yet Checked" }}
                                {% if result.device.status and result.device.warranty %} <em>- Covered By Warranty </em>{% endif %}

                            </td>
                            <td>
                                {% for item in result.accessory %}
                                <p> {{ item.accessory.name }}: {{ item.get_status_display|default:"Not Yet Checked" }} {% if item.status and item.warranty %} <em>- Covered By Warranty </em>{% endif %}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>

        </div>
    </div>



{% endblock %}

ProcessManager/templates/ProcessManager/checkin_select_person.html
{% extends 'ProcessManager/select_person.html' %}

{% block title %} Select Person {% endblock %}

{% block person_search_action %} {% url 'checkin_search_person' check_in.id %}{% endblock %}


{% block content %}

<div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"> Pick an assignment <b id="id_result_count"></b></div>
                <div class="panel-body">
                <table class="table table-bordered table-condensed table-hover" id="id_person_table">
                    <thead> <th> Name</th> <th> Student ID</th> <th> Date of Birth</th> <th> Assignment</th></thead>
                    {% for person in persons_information %}
                        {% for assignment in person.assignment_set.all %}
                            {% if assignment.active %}
                    <tr class="clickable_row" id="id_person_link_{{ person.id }}" data-url="{% url 'device_check_in' check_in.id assignment.id %}"><td>{{ person.first_name}} {{ person.middle_name|slice:":1" }} {{ person.last_name }}</td>
                        <td>{{ person.student_number }}</td><td>{{ person.birthdate|date:"m-d-Y" }}</td><td> {{ assignment.id }}</td></tr>
                            {% endif %}
                            {% endfor %}
                    {% endfor %}
                </table>
                </div>
            </div>
        </div>

    </div>



{%  endblock %}

ProcessManager/templates/ProcessManager/person.html
{% extends 'ProcessManager/base.html' %}
{% load staticfiles %}
{% block title %} Select Person {% endblock %}

{% block content %}
    <div class="row">
    <div class="col-md-6 col-sm-12">

        <div class="panel panel-default">
            <div class="panel-heading">{{ person_information.first_name}} {{ person_information.middle_name|slice:":1" }} {{ person_information.last_name }} </div>
                <div class="panel-body">
                    <img src="{% static 'person_pictures/' %}{{ person_information.student_number }}.jpg" class="img-rounded thumbnail img-responsive col-md-2 col-sm-2 col-xs-2" alt="{{ person_information.student_number }}">
                   <div class="col-md-10 col-sm-10 col-xs-10">
                    <table class="table table-striped table-bordered table-condensed table-responsive" id="id_person_table">
                        <tr><td>Name</td><td >{{ person_information.first_name}} {{ person_information.middle_name|slice:":1" }} {{ person_information.last_name }}</td></tr>
                        <tr><td>Student Number</td><td>{{ person_information.student_number }}</td></tr>
                        <tr><td>Date of Birth</td><td>{{ person_information.birthdate }}</td></tr>
                    </table>
                </div>

            </div>
        </div>
    </div>


    <div class="col-md-6 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"> Notes</div>
            <div class="panel-body" id="id_notes_box">

            {% for note in person_information.note_set.all %}
                {{ note.content }}
             {% endfor %}
             </div>
        </div>
    </div>
 </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"> Device Assignment History</div>
                <div class="panel-body">
                <table class="table table-responsive table-striped table-bordered table-condensed" id="id_asset_history_table">
                 <thead> <th> Asset Tag</th> <th>Type</th><th>Start Date</th><th>End Date</th> </thead>
                    {% for assignment in person_information.assignment_set.all %}
                    <tr {% if assignment.active %}class="active"{% endif %}>
                        <td class="col-md-2 col-sm-2 col-xs-3" id="id_asset_{{ assignment.asset.tag }}"><a href="/asset/{{ assignment.asset.tag }}/">{{ assignment.asset.tag }} </a></td>
                        <td class="col-md-3 col-sm-3 col-xs-3">{{ assignment.asset.type.name}}</td>
                        <td class="col-md-2 col-sm-2 col-xs-3">{{ assignment.start_date|date:"m-d-Y" }}</td>

                        <td class="col-md-4 col-sm-4 col-xs-3">
                            <form class="form-inline full_span_input" method="POST" action="{% url 'assignment_end_date' assignment.id %}">
                                <div class="form-group">
                                    <label class="sr-only" for="id_end_date_assignment_box"> </label>
                                <div class="input-group">
                                     <input type="text" name="end_date" class="form-control date_picker" value="{{ assignment.end_date|date:"m-d-Y"  }}" id="id_add_end_date_box_{{ assignment.id }}">
                                    <span class="input-group-btn">
                                        <button tyupe="submit" class="btn btn-default" id="id_add_end_date_{{ assignment.id }}" aria-label="Add End Date">
                                            <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                                        </button>
                                    </span>
                                </div>
                                </div>
                                {% csrf_token %}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                </div>
            </div>
        </div>

    </div>

{% endblock %}